### ISSUE TITLE
Heatmap is distorted when glyph contains (self-)intersections

### ISSUE THREAD

**Issue by madig** [simoncozens/Heatmap#5]
![screenshot 2017-07-08 09 13 45](https://user-images.githubusercontent.com/380829/27983502-cb1a8774-63bd-11e7-997b-6174ec996db2.png)

This makes the plugin useless on many glyphs I'm editing. Also, the Speedpunk plugin breaks. Suggestion: Create an intermediate glyph with removed overlap and calculate heatmap on that, then overlay it onto the actual glyph.

**Comment by simoncozens** [comment]
This was fixed in cb7edd9 but I guess I didn't release a new binary. Have a look at https://github.com/simoncozens/Heatmap/releases/tag/1.0

**Comment by madig** [comment]
Uh, the edit view blanks now on activation.

**Comment by madig** [comment]
Alright, no idea what happend, but on the preview version of Glyphs, it works as expected.

**Comment by manu-del** [comment]
Is the plugin supposed to show the heatmap without overlaps now? It looks like the issue is still happening with the last version, on Glyphs 3
![Capture d’écran 2021-08-17 à 11 31 18](https://user-images.githubusercontent.com/38568274/129701337-f0c20aba-778f-4047-9075-8ddce5fb122f.png)
